### ISSUE TITLE
[CardBoard] 카드 상태별 조회 기능 구현

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/wedding-planner-backend#73]
## 🖊️ *Description*
userId와 cardIds를 가지고 있는 카드보드가 card의 상태별 카드 조회 로직을 이용해서 user의 카드 상태별로 리턴하는 기능을 구현한다.
## ✅ *Todo*
- [ ] Card 서비스에 cardIds 전달할 DTO 객체 생성
- [ ] CardBoard가 위 DTO를 전달하고 user의 카드객체를 요청하는 로직 구현
- [x] Card의 기존 상태에 따른 조회 API 리팩토링
  - 하위티켓으로 분리하기 #74 
- [ ] CardBoard에 카드 상태별로 담긴 List가 있는 DTO 를 반환하는 로직 구현
